In [1]:
%timeit [i**4 for i in range(1,9)]

1.87 µs ± 44.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [2]:
import numpy as np
%timeit np.arange(1,9)**4

1.65 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array

In [1]:
import numpy as np

x = [1,2,3,4]
y = np.array(x)

print(y)

[1 2 3 4]


In [3]:
import numpy as np

y = np.array([1,2,3,4])

print(y)
print(type(y))
y

[1 2 3 4]
<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [4]:
l = []

for i in range(1,5):
    data = int(input("Enter data "))
    l.append(data)
    
y = np.array(l)
print(y)
print(type(y))
print(y.ndim)

Enter data  11
Enter data  12
Enter data  13
Enter data  14


[11 12 13 14]
<class 'numpy.ndarray'>
1


In [5]:
ar2d = np.array([[1,2,3,4],[17,15,14,12]])
print(ar2d)
print(ar2d.ndim)

[[ 1  2  3  4]
 [17 15 14 12]]
2


In [6]:
ar3d = np.array([[[1,2,3,4],[17,15,14,12]],[[5,6,7,8]]])
print(ar3d)
print(ar3d.ndim)

[list([[1, 2, 3, 4], [17, 15, 14, 12]]) list([[5, 6, 7, 8]])]
1


C:\Users\Akshay Soni\AppData\Local\Temp\ipykernel_9096\1151516850.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar3d = np.array([[[1,2,3,4],[17,15,14,12]],[[5,6,7,8]]])


In [8]:
ar3d = np.array([[[1,2,3,4],[17,15,14,12]],[[5,6,7,8],[11,22,33,44]]])
print(ar3d)
print(ar3d.ndim)

[[[ 1  2  3  4]
  [17 15 14 12]]

 [[ 5  6  7  8]
  [11 22 33 44]]]
3


In [11]:
arNd = np.array([1,2,3,4],ndmin = 10)
print(arNd)
print(arNd.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Numpy Array Functions

In [13]:
arZeros = np.zeros(4)
print(arZeros)

[0. 0. 0. 0.]


In [15]:
arZeros2d = np.zeros((3,4))
print(arZeros2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
arOnes = np.ones(4)
print(arOnes)

[1. 1. 1. 1.]


In [17]:
arOnes2d = np.ones((4,3))
print(arOnes2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arEmpty = np.empty(4)
print(arEmpty)

[1. 1. 1. 1.]


In [20]:
arEmpty2d = np.empty((3,3))
print(arEmpty2d)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.85365637e-321]
 [5.98147296e-154 6.01346930e-154 4.19314256e+228]]


In [21]:
arRange = np.arange(4)
print(arRange)

[0 1 2 3]


In [22]:
arRange = np.arange(1,11,2)
print(arRange)

[1 3 5 7 9]


In [23]:
arDiagonal = np.eye(3)
print(arDiagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
arDiagonal = np.eye(3,5)
print(arDiagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [25]:
arLin = np.linspace(0,20,num=5)
print(arLin)

[ 0.  5. 10. 15. 20.]


In [26]:
arLin = np.linspace(0,20,num=2)
print(arLin)

[ 0. 20.]


In [27]:
arLin = np.linspace(0,10,num=5)
print(arLin)

[ 0.   2.5  5.   7.5 10. ]
