In [7]:
%timeit [i**4 for i in range(1,9)]

5.27 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
import numpy as np
%timeit np.arange(1,9)**4

4.22 µs ± 870 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
import numpy as np

# Array

In [1]:
import numpy as np

x = [1,2,3,4]
y = np.array(x)

print(y)

[1 2 3 4]


In [3]:
import numpy as np

y = np.array([1,2,3,4])

print(y)
print(type(y))
y

[1 2 3 4]
<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [4]:
l = []

for i in range(1,5):
    data = int(input("Enter data "))
    l.append(data)
    
y = np.array(l)
print(y)
print(type(y))
print(y.ndim)

Enter data  11
Enter data  12
Enter data  13
Enter data  14


[11 12 13 14]
<class 'numpy.ndarray'>
1


In [5]:
ar2d = np.array([[1,2,3,4],[17,15,14,12]])
print(ar2d)
print(ar2d.ndim)

[[ 1  2  3  4]
 [17 15 14 12]]
2


In [6]:
ar3d = np.array([[[1,2,3,4],[17,15,14,12]],[[5,6,7,8]]])
print(ar3d)
print(ar3d.ndim)

[list([[1, 2, 3, 4], [17, 15, 14, 12]]) list([[5, 6, 7, 8]])]
1


C:\Users\Akshay Soni\AppData\Local\Temp\ipykernel_9096\1151516850.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar3d = np.array([[[1,2,3,4],[17,15,14,12]],[[5,6,7,8]]])


In [8]:
ar3d = np.array([[[1,2,3,4],[17,15,14,12]],[[5,6,7,8],[11,22,33,44]]])
print(ar3d)
print(ar3d.ndim)

[[[ 1  2  3  4]
  [17 15 14 12]]

 [[ 5  6  7  8]
  [11 22 33 44]]]
3


In [11]:
arNd = np.array([1,2,3,4],ndmin = 10)
print(arNd)
print(arNd.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Numpy Array Functions

In [13]:
arZeros = np.zeros(4)
print(arZeros)

[0. 0. 0. 0.]


In [15]:
arZeros2d = np.zeros((3,4))
print(arZeros2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
arOnes = np.ones(4)
print(arOnes)

[1. 1. 1. 1.]


In [17]:
arOnes2d = np.ones((4,3))
print(arOnes2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arEmpty = np.empty(4)
print(arEmpty)

[1. 1. 1. 1.]


In [20]:
arEmpty2d = np.empty((3,3))
print(arEmpty2d)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.85365637e-321]
 [5.98147296e-154 6.01346930e-154 4.19314256e+228]]


In [21]:
arRange = np.arange(4)
print(arRange)

[0 1 2 3]


In [22]:
arRange = np.arange(1,11,2)
print(arRange)

[1 3 5 7 9]


In [23]:
arDiagonal = np.eye(3)
print(arDiagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
arDiagonal = np.eye(3,5)
print(arDiagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [25]:
arLin = np.linspace(0,20,num=5)
print(arLin)

[ 0.  5. 10. 15. 20.]


In [26]:
arLin = np.linspace(0,20,num=2)
print(arLin)

[ 0. 20.]


In [27]:
arLin = np.linspace(0,10,num=5)
print(arLin)

[ 0.   2.5  5.   7.5 10. ]


# Random Number Array

In [28]:
ranArr = np.random.rand(4)
print(ranArr)

[0.28612951 0.63929834 0.87970048 0.70254987]


In [29]:
ranArr2d = np.random.rand(4,3)
print(ranArr2d)

[[0.61647706 0.153595   0.25600379]
 [0.12445997 0.52261762 0.82796977]
 [0.58729041 0.59651725 0.4371282 ]
 [0.50066541 0.57542598 0.32315935]]


In [30]:
ranArrNegative = np.random.randn(4)
print(ranArrNegative)

[-0.27052385 -0.46323798  1.14337485 -0.91336412]


In [31]:
ranArrNegative2d = np.random.randn(3,2)
print(ranArrNegative2d)

[[ 1.04839043  0.12069216]
 [-1.37378843  0.79132311]
 [ 0.40240003  0.51488638]]


In [33]:
ranArr = np.random.ranf(4)
print(ranArr)

[0.53349371 0.23127002 0.35354352 0.26901235]


In [35]:
ranArr2d = np.random.ranf((3,2))
print(ranArr2d)

[[0.70041082 0.75224649]
 [0.2575867  0.5596336 ]
 [0.07307599 0.37563185]]


In [37]:
ranArr = np.random.randint(2,20,5)
print(ranArr)

[11  7 10  7  2]


In [38]:
ranArr = np.random.randint(2,20,(3,2))
print(ranArr)

[[ 6  7]
 [15 18]
 [ 3 10]]


In [39]:
ranArr = np.random.random_integers(3)
print(ranArr)

1


C:\Users\Akshay Soni\AppData\Local\Temp\ipykernel_9096\86191777.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  ranArr = np.random.random_integers(3)


In [40]:
ranArr = np.random.random(3,)
print(ranArr)

[0.09556365 0.10349263 0.44060316]


In [42]:
arr = np.arange(12)
print(arr)
np.random.shuffle(arr)  
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  9 11  7  4  1  0  6  8  5 10  2]


# Numpy Data Type

In [9]:
x = np.array([1,2,3,4])
print("data type :",x.dtype)

data type : int32


In [10]:
x = np.array([1.2,2.45,3.14,4.2])
print("data type :",x.dtype)

data type : float64


In [11]:
x = np.array(["Hello","C",'Program'])
print("data type :",x.dtype)

data type : <U7


In [12]:
x = np.array(["H","C",'P'])
print("data type :",x.dtype)

data type : <U1


In [13]:
x = np.array(["H","C",'P',1,2,3])
print("data type :",x.dtype)

data type : <U11


In [14]:
x = np.array(["H","C",'P',1,2.35,3])
print("data type :",x.dtype)

data type : <U32


In [15]:
x = np.array([1,2,3,4],dtype=np.int8)
print("data type :",x.dtype)

data type : int8


In [16]:
x = np.array([1,2,3,4],dtype=np.int64)
print("data type :",x.dtype)

data type : int64


In [17]:
x = np.array([1,2,3,4],dtype='f')
print("data type :",x.dtype)

data type : float32


In [18]:
x = np.array([1,2,3,4],dtype=np.float64)
print("data type :",x.dtype)

data type : float64


In [19]:
x = np.array([1,2,3,4])
y = np.float32(x)

print(x,x.dtype)
print(y,y.dtype)

[1 2 3 4] int32
[1. 2. 3. 4.] float32


In [21]:
x = np.array([1,2,3,4])
y = x.astype(float)

print(x,x.dtype)
print(y,y.dtype)

[1 2 3 4] int32
[1. 2. 3. 4.] float64


# Arithmetic Operations

In [22]:
x = np.array([1,4,9,7])
y = x + 2

print(y)

[ 3  6 11  9]


In [23]:
x = np.array([1,4,9,7])

y = x + 2
print(y)

y = x - 2
print(y)

y = x * 2
print(y)

y = x / 2
print(y)

y = x % 2
print(y)

y = x ** 2
print(y)

[ 3  6 11  9]
[-1  2  7  5]
[ 2  8 18 14]
[0.5 2.  4.5 3.5]
[1 0 1 1]
[ 1 16 81 49]


In [25]:
x = np.array([1,4,9,7])
y = np.array([3,11,4,6])

z = x + y
print(z)

z = x - y
print(z)

z = x * y
print(z)

z = x / y
print(z)

[ 4 15 13 13]
[-2 -7  5  1]
[ 3 44 36 42]
[0.33333333 0.36363636 2.25       1.16666667]


In [26]:
x = np.array([1,4,9,7])
y = np.array([3,11,4,6,22])

z = x + y
print(z)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [28]:
x = np.array([1,4,9,7])

y = np.add(x,2)
print(y)

y = np.subtract(x,2)
print(y)

y = np.multiply(x,2)
print(y)

y = np.divide(x,2)
print(y)

y = np.mod(x,2)
print(y)

y = np.power(x,2)
print(y)

[ 3  6 11  9]
[-1  2  7  5]
[ 2  8 18 14]
[0.5 2.  4.5 3.5]
[1 0 1 1]
[ 1 16 81 49]


In [34]:
x = np.array([1,4,9,7])
y = np.array([3,11,4,6])
t = np.array([2,3,4,5])

z = np.add(x,y,t)
print(z)

[ 4 15 13 13]


In [35]:
x = np.array([[1,2,3],[1,2,3]])
y = np.array([[11,12,13],[4,5,6]])

print(x)
print()
print(y)
print()

z = x + y
print(z)

[[1 2 3]
 [1 2 3]]

[[11 12 13]
 [ 4  5  6]]

[[12 14 16]
 [ 5  7  9]]


In [36]:
x = np.array([[1,2,3],[1,2,3]])
y = np.array([[11,12,13],[4,5,6]])

print(x)
print()
print(y)
print()

z = x - y
print(z)

[[1 2 3]
 [1 2 3]]

[[11 12 13]
 [ 4  5  6]]

[[-10 -10 -10]
 [ -3  -3  -3]]


In [37]:
x = np.array([[1,2,3],[1,2,3]])
y = np.array([[11,12,13],[4,5,6]])

print(x)
print()
print(y)
print()

z = x * y
print(z)

[[1 2 3]
 [1 2 3]]

[[11 12 13]
 [ 4  5  6]]

[[11 24 39]
 [ 4 10 18]]


In [2]:
x = np.array([78,54,98,0,12,98,7,-4,44])

print("Minimum :",np.min(x),np.argmin(x))
print("Maximum :",np.max(x),np.argmax(x))

Minimum : -4 7
Maximum : 98 2


In [9]:
x = np.array([1,9,3,16])

print("square root :",np.sqrt(x))

square root : [1.         3.         1.73205081 4.        ]


In [4]:
x = np.array([[1,9,3],[2,4,6]])

print("Minimum :",np.min(x,axis=1),np.argmin(x,axis=1))
print("Maximum :",np.max(x,axis=1),np.argmax(x,axis=1))

Minimum : [1 2] [0 0]
Maximum : [9 6] [1 2]


In [5]:
x = np.array([[1,9,3],[2,4,6]])

print("Minimum :",np.min(x,axis=0),np.argmin(x,axis=0))
print("Maximum :",np.max(x,axis=0),np.argmax(x,axis=0))

Minimum : [1 4 3] [0 1 0]
Maximum : [2 9 6] [1 0 1]


In [8]:
x = np.array([[1,9,3],[2,4,6]])

print("square root :",np.sqrt(x))

square root : [[1.         3.         1.73205081]
 [1.41421356 2.         2.44948974]]


In [10]:
x = np.array([1,60,90])
y = np.array([[30,60,90],[180,270,360]])

print("Sin :",np.sin(x))
print("Sin :",np.sin(y))

Sin : [ 0.84147098 -0.30481062  0.89399666]
Sin : [[-0.98803162 -0.30481062  0.89399666]
 [-0.80115264 -0.17604595  0.95891572]]


In [11]:
x = np.array([1,60,90])
y = np.array([[30,60,90],[180,270,360]])

print("Cos :",np.cos(x))
print("Cos :",np.cos(y))

Cos : [ 0.54030231 -0.95241298 -0.44807362]
Cos : [[ 0.15425145 -0.95241298 -0.44807362]
 [-0.59846007  0.98438195 -0.28369109]]


In [12]:
x = np.array([1,9,3])

print("Cummulative Sum :",np.cumsum(x))

Cummulative Sum : [ 1 10 13]


In [13]:
x = np.array([[1,9,3],[1,2,3]])

print("Cummulative Sum :",np.cumsum(x))

Cummulative Sum : [ 1 10 13 14 16 19]


In [14]:
x = np.array([[1,9,3],[1,2,3]])

print("Cummulative Sum :",np.cumsum(x,axis=0))

Cummulative Sum : [[ 1  9  3]
 [ 2 11  6]]


In [15]:
x = np.array([[1,9,3],[1,2,3]])

print("Cummulative Sum :",np.cumsum(x,axis=1))

Cummulative Sum : [[ 1 10 13]
 [ 1  3  6]]


# Shape

In [17]:
x = np.array([1,2,3,4])

print(x)
print(x.shape)

[1 2 3 4]
(4,)


In [18]:
x = np.array([[1,2,3,4],[9,8,7,6]])

print(x)
print(x.shape)

[[1 2 3 4]
 [9 8 7 6]]
(2, 4)


In [19]:
x = np.array([1,2,3,4],ndmin=4)

print(x)
print(x.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [21]:
x = np.array([1,2,3,4,5,6])
print(x)
print("Shape",x.shape,"Dimension",x.ndim)

print()

y = x.reshape(3,2)
print(y)
print("Shape",y.shape,"Dimension",y.ndim)

[1 2 3 4 5 6]
Shape (6,) Dimension 1

[[1 2]
 [3 4]
 [5 6]]
Shape (3, 2) Dimension 2


In [22]:
x = np.array([1,2,3,4,5,6])
print(x)
print("Shape",x.shape,"Dimension",x.ndim)

print()

y = x.reshape(3,3)
print(y)
print("Shape",y.shape,"Dimension",y.ndim)

[1 2 3 4 5 6]
Shape (6,) Dimension 1



ValueError: cannot reshape array of size 6 into shape (3,3)

In [23]:
x = np.array([1,2,3,4,5,6])
print(x)
print("Shape",x.shape,"Dimension",x.ndim)

print()

y = x.reshape(2,2)
print(y)
print("Shape",y.shape,"Dimension",y.ndim)

[1 2 3 4 5 6]
Shape (6,) Dimension 1



ValueError: cannot reshape array of size 6 into shape (2,2)

In [24]:
x = np.array([1,2,3,4,5,6])
print(x)
print("Shape",x.shape,"Dimension",x.ndim)

print()

y = x.reshape(2,3)
print(y)
print("Shape",y.shape,"Dimension",y.ndim)

[1 2 3 4 5 6]
Shape (6,) Dimension 1

[[1 2 3]
 [4 5 6]]
Shape (2, 3) Dimension 2


In [25]:
x = np.arange(12)
print(x)
print("Shape",x.shape,"Dimension",x.ndim)

print()

y = x.reshape(2,3,2)
print(y)
print("Shape",y.shape,"Dimension",y.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape (12,) Dimension 1

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Shape (2, 3, 2) Dimension 3


In [26]:
x = np.array([[[0,1],[2,3],[4,5]],[[6,7],[8,9],[10,11]]])
print(x)
print("Shape",x.shape,"Dimension",x.ndim)

print()

y = x.reshape(-1)
print(y)
print("Shape",y.shape,"Dimension",y.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Shape (2, 3, 2) Dimension 3

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape (12,) Dimension 1


# Broadcasting

In [3]:
x = np.array([1,2,3,4])
y = np.array([1,2,3])

print(x+y)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

print(x+y)

[ 5  7  9 11]


In [6]:
x = np.array([1,2,3,4])
print(x,x.shape)
print()

y = np.array([[1],[2],[3],[4]])
print(y,y.shape)
print()

z = x+y
print(z,z.shape)

[1 2 3 4] (4,)

[[1]
 [2]
 [3]
 [4]] (4, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] (4, 4)


In [7]:
x = np.array([[4],[6]])
print(x,x.shape)
print()

y = np.array([[1,3],[2,7]])
print(y,y.shape)
print()

z = x+y
print(z,z.shape)

[[4]
 [6]] (2, 1)

[[1 3]
 [2 7]] (2, 2)

[[ 5  7]
 [ 8 13]] (2, 2)


In [8]:
x = np.array([4,6])
print(x,x.shape)
print()

y = np.array([[1,3],[2,7]])
print(y,y.shape)
print()

z = x+y
print(z,z.shape)

[4 6] (2,)

[[1 3]
 [2 7]] (2, 2)

[[ 5  9]
 [ 6 13]] (2, 2)


# Array Indexing

In [3]:
x = np.array([10,11,12,13]) # index are 0 1 2 3 or -4 -3 -2 -1

print(x[1])
print(x[-3])

11
11


In [12]:
x = np.array([[10,11,12,13],[23,24,25,26]])

print(x)
print(x[1,2])

[[10 11 12 13]
 [23 24 25 26]]
25


In [13]:
x = np.array([[[10,11,12,13],[23,24,25,26]],[[2,3,4,5],[33,34,35,36]]])

print(x)
print(x[1,1,2])

[[[10 11 12 13]
  [23 24 25 26]]

 [[ 2  3  4  5]
  [33 34 35 36]]]
35


# Slicing

In [19]:
x = np.array([21,22,23,24,25,26])
#             0  1  2  3  4  5

print("22 to 25",x[1:5])
print("21 to 24",x[:4])
print("23 to 26",x[2:])

print("21 to 26",x[:])

#steps

print("22 to 25 steps 2",x[1:5:2])
print("21 to 25 steps 2",x[:5:2])
print("22 to 26 steps 2",x[1::2])
print("21 to 26 steps 2",x[::2])


22 to 25 [22 23 24 25]
21 to 24 [21 22 23 24]
23 to 26 [23 24 25 26]
21 to 26 [21 22 23 24 25 26]
22 to 25 steps 2 [22 24]
21 to 25 steps 2 [21 23 25]
22 to 26 steps 2 [22 24 26]
21 to 26 steps 2 [21 23 25]


In [21]:
x = np.array([[4,5,6,7,8,9,10],[11,12,13,14,15,16,17],[20,21,22,23,24,25,26]])

print("12 to 16 step 2",x[1,1:6:2])
print("20 to 24",x[2,:5])

12 to 16 step 2 [12 14 16]
20 to 24 [20 21 22 23 24]


In [22]:
x = np.array([[
    [2,3,4,5,6],[7,8,9,10,11]
],[
    [12,13,14,15,16],[17,18,19,20,21]
]])

print("13 to 15",x[1,0,1:4])

13 to 15 [13 14 15]


# Iteration

In [25]:
x = np.array([19,18,17,16,15,14,13,12])

print(x)
print()

for i in x:
    print(i)

[19 18 17 16 15 14 13 12]

19
18
17
16
15
14
13
12


In [27]:
x = np.array([[4,5,6,7,8,9,10],[11,12,13,14,15,16,17],[20,21,22,23,24,25,26]])


for i in x:
    print(i)

[ 4  5  6  7  8  9 10]
[11 12 13 14 15 16 17]
[20 21 22 23 24 25 26]


In [28]:
x = np.array([[4,5,6,7,8,9,10],[11,12,13,14,15,16,17],[20,21,22,23,24,25,26]])


for i in x:
    for j in i:
        print(j)

4
5
6
7
8
9
10
11
12
13
14
15
16
17
20
21
22
23
24
25
26


In [29]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

print(x)

[[[ 2  3  4  5  6]
  [ 7  8  9 10 11]]

 [[12 13 14 15 16]
  [17 18 19 20 21]]]


In [30]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

for i in x:
    print(i)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[12 13 14 15 16]
 [17 18 19 20 21]]


In [31]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

for i in x:
    for j in i:
        print(j)

[2 3 4 5 6]
[ 7  8  9 10 11]
[12 13 14 15 16]
[17 18 19 20 21]


In [32]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

for i in x:
    for j in i:
        for k in j:
            print(k)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [34]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

for i in np.nditer(x):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [37]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

for i in np.ndenumerate(x):
    print(i)

((0, 0, 0), 2)
((0, 0, 1), 3)
((0, 0, 2), 4)
((0, 0, 3), 5)
((0, 0, 4), 6)
((0, 1, 0), 7)
((0, 1, 1), 8)
((0, 1, 2), 9)
((0, 1, 3), 10)
((0, 1, 4), 11)
((1, 0, 0), 12)
((1, 0, 1), 13)
((1, 0, 2), 14)
((1, 0, 3), 15)
((1, 0, 4), 16)
((1, 1, 0), 17)
((1, 1, 1), 18)
((1, 1, 2), 19)
((1, 1, 3), 20)
((1, 1, 4), 21)


In [36]:
x = np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[12,13,14,15,16],[17,18,19,20,21]]])

for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0, 0) 2
(0, 0, 1) 3
(0, 0, 2) 4
(0, 0, 3) 5
(0, 0, 4) 6
(0, 1, 0) 7
(0, 1, 1) 8
(0, 1, 2) 9
(0, 1, 3) 10
(0, 1, 4) 11
(1, 0, 0) 12
(1, 0, 1) 13
(1, 0, 2) 14
(1, 0, 3) 15
(1, 0, 4) 16
(1, 1, 0) 17
(1, 1, 1) 18
(1, 1, 2) 19
(1, 1, 3) 20
(1, 1, 4) 21


# Copy and View

In [3]:
x = np.array([11,12,13,14])

c = x.copy()

x[2] = 23

print("x :",x)
print("c :",c)

x : [11 12 23 14]
c : [11 12 13 14]


In [4]:
x = np.array([11,12,13,14])

c = x.copy()

c[2] = 23

print("x :",x)
print("c :",c)

x : [11 12 13 14]
c : [11 12 23 14]


In [5]:
x = np.array([11,12,13,14])

v = x.view()

x[2] = 23

print("x :",x)
print("v :",v)

x : [11 12 23 14]
v : [11 12 23 14]


In [6]:
x = np.array([11,12,13,14])

v = x.view()

v[3] = 23

print("x :",x)
print("v :",v)

x : [11 12 13 23]
v : [11 12 13 23]


In [8]:
x = np.array([11,12,13,14])

v = x.view()
c = x.copy()

print("base of x:",x.base)
print("base of v:",v.base)
print("base of c:",c.base)

base of x: None
base of v: [11 12 13 14]
base of c: None


# Join

In [2]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

z = np.concatenate((x,y))

print(z)

[1 2 3 4 9 8 7 6]


In [4]:
x = np.array([[1,2],[3,4]])
y = np.array([[9,8],[7,6]])

z = np.concatenate((x,y),axis=0)

print(z)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [5]:
x = np.array([[1,2],[3,4]])
y = np.array([[9,8],[7,6]])

z = np.concatenate((x,y),axis=1)

print(z)

[[1 2 9 8]
 [3 4 7 6]]


In [6]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

z = np.stack((x,y),axis=0)

print(z)

[[1 2 3 4]
 [9 8 7 6]]


In [7]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

z = np.stack((x,y),axis=1)

print(z)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [8]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

z = np.vstack((x,y))

print(z)

[[1 2 3 4]
 [9 8 7 6]]


In [9]:
x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

z = np.hstack((x,y))

print(z)

[1 2 3 4 9 8 7 6]


# Split

In [12]:
x = np.array([1,2,3,4,5,6,7,8])

print(x)
print()

y = np.array_split(x,2)

print(y)
print()

y = np.array_split(x,3)

print(y)
print()

print(y[0])

[1 2 3 4 5 6 7 8]

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

[1 2 3]


In [13]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])

print(x)
print()

y = np.array_split(x,2)

print(y)
print()

y = np.array_split(x,2,axis=1)

print(y)
print()

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]



# Search

In [2]:
x = np.array([1,2,3,4,2,5,6,2,7,8,9])

y = np.where(x == 2)
print(y)

(array([1, 4, 7], dtype=int64),)


In [3]:
x = np.array([1,2,3,4,2,5,6,2,7,8,9])

y = np.where(x%2 == 0)
print(y)

(array([1, 3, 4, 6, 7, 9], dtype=int64),)


In [4]:
x = np.array([1,2,3,4,2,5,6,2,7,8,9])

y = np.where(x > 4)
print(y)

(array([ 5,  6,  8,  9, 10], dtype=int64),)


In [6]:
x = np.array([12,24,56,8,33,88,75,42,3])

y = np.where((x > 18 and x < 60))
print(y)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]:
x = np.array([12,24,56,8,33,88,75,42,3])

y = np.where(60>x>18)
print(y)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
x = np.array([10,11,12,13,14,19,20,21])

y = np.searchsorted(x,16)
print(y)

5


In [11]:
x = np.array([10,11,12,13,14,19,20,21])

y = np.searchsorted(x,15,side="right")
print(y)

5


In [18]:
x = np.array([10,11,12,13,14,17,18,19,20,21])

y = np.searchsorted(x,[15,16,17],side="right")
print(y)

[5 5 6]


In [19]:
x = np.array([10,11,12,13,14,17,18,19,20,21])

y = np.searchsorted(x,[15,16,17])
print(y)

[5 5 5]


# Sort

In [20]:
x = np.array([12,5,45,32,26,11,8,65,77,6,3])

y = np.sort(x)

print(y)

[ 3  5  6  8 11 12 26 32 45 65 77]


In [21]:
x = np.array([[12,5,45],[32,26,11],[8,65,77],[6,-3,44]])

y = np.sort(x)

print(y)

[[ 5 12 45]
 [11 26 32]
 [ 8 65 77]
 [-3  6 44]]


In [22]:
x = np.array(['q','r','e','s','l','a'])

y = np.sort(x)

print(y)

['a' 'e' 'l' 'q' 'r' 's']


In [23]:
x = np.array(['Akshay','Sumit','Jay','Vijay','Vikas','a'])

y = np.sort(x)

print(y)

['Akshay' 'Jay' 'Sumit' 'Vijay' 'Vikas' 'a']
